name: Terraform Quality Gate

on:
  pull_request:

jobs:
  terraform-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Install Snyk
        uses: snyk/actions/setup@master

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

#      - name: Run Snyk IaC Scan
#        run: snyk iac test .
#        continue-on-error: true
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '18'

#      - name: Install Dependencies
#        run: npm install

#      - name: Run Snyk SCA Scan
#        run: snyk test
#        continue-on-error: true
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

#      - name: Run Snyk SAST Scan
#        run: snyk code test
#        continue-on-error: true
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Build Docker Image
        run: docker build -t lab-container:latest .

      - name: Run Snyk Container Scan
        run: snyk container test lab-container:latest --file=Dockerfile
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
